// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package orm

import "github.com/hinego/gfen/ssr"

func NewOrm() ssr.IOrm {
	return &sOrm{}
}
func init() {

	ssr.RegisterOrm(NewOrm())
}