// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package dao

import "github.com/hinego/gfen/ssr"

func NewDao() ssr.IDao {
	return &sDao{}
}
func init() {

	ssr.RegisterDao(NewDao())
}
