// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import "github.com/hinego/gfen/ssr"

func NewLogic() ssr.ILogic {
	return &sLogic{}
}
func init() {

	ssr.RegisterLogic(NewLogic())
}