// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package ssr

import (
	"github.com/hinego/gfen/genx"
)

type (
	ICtrl interface {
		Generate(data *genx.ApiInput) (err error)
	}
)

var (
	localCtrl ICtrl
)

func Ctrl() ICtrl {
	if localCtrl == nil {
		panic("implement not found for interface ICtrl, forgot register?")
	}
	return localCtrl
}

func RegisterCtrl(i ICtrl) {
	localCtrl = i
}
