// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package ssr

import (
	"github.com/hinego/gfen/genx"
)

type (
	IDao interface {
		Generate(data *genx.DaoInput) (err error)
		GenModel(data *genx.DaoInput) (err error)
	}
)

var (
	localDao IDao
)

func Dao() IDao {
	if localDao == nil {
		panic("implement not found for interface IDao, forgot register?")
	}
	return localDao
}

func RegisterDao(i IDao) {
	localDao = i
}
