// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package ssr

import (
	"github.com/hinego/gfen/horm"
)

type (
	IHorm interface {
		Generate(in *horm.Input) (err error)
	}
)

var (
	localHorm IHorm
)

func Horm() IHorm {
	if localHorm == nil {
		panic("implement not found for interface IHorm, forgot register?")
	}
	return localHorm
}

func RegisterHorm(i IHorm) {
	localHorm = i
}
