// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package ssr

import (
	"github.com/hinego/gfen/genx"
)

type (
	ILogic interface {
		Parse(in *genx.LogicInput) (err error)
	}
)

var (
	localLogic ILogic
)

func Logic() ILogic {
	if localLogic == nil {
		panic("implement not found for interface ILogic, forgot register?")
	}
	return localLogic
}

func RegisterLogic(i ILogic) {
	localLogic = i
}
