// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package ssr

import (
	"github.com/hinego/gfen/genx"
)

type (
	IOrm interface {
		Generate(data *genx.DaoInput) (err error)
		GenModel(data *genx.DaoInput) (err error)
	}
)

var (
	localOrm IOrm
)

func Orm() IOrm {
	if localOrm == nil {
		panic("implement not found for interface IOrm, forgot register?")
	}
	return localOrm
}

func RegisterOrm(i IOrm) {
	localOrm = i
}
