// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package horm

import "github.com/hinego/gfen/ssr"

func NewHorm() ssr.IHorm {
	return &sHorm{}
}
func init() {

	ssr.RegisterHorm(NewHorm())
}
