// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/hinego/gfen/logic/ctrl"
	_ "github.com/hinego/gfen/logic/dao"
	_ "github.com/hinego/gfen/logic/gen"
	_ "github.com/hinego/gfen/logic/logic"
)
