// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package ctrl

import "github.com/hinego/gfen/ssr"

func NewCtrl() ssr.ICtrl {
	return &sCtrl{}
}
func init() {

	ssr.RegisterCtrl(NewCtrl())
}